name: "bluebull"
mode: "dev"
port: 8081
version: "v0.0.1"
start_time: "2021-09-01"
machine_id: 1

log:
  level: "debug"
  filename: "bluebull_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "localhost"
  port: 3306
  user: "root"
  password: "zhangyan"
  dbname: "bluebell"
  max_open_conns: 200
  max_idle_conns: 50

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  pool_size: 100